USE Proyecto_Veterinaria
GO



--Vista--

CREATE VIEW vw_Directorio_General
AS
SELECT PERSONA.CEDULA AS Cedula_Cliente,
PERSONA.NOMBRE AS Nombre_Cliente,
PERSONA.CORREO AS Correo_Cliente,
CONCAT(PERSONA.CALLE, ' ', PERSONA.NOMBRE, ', ' , PERSONA.SECTOR) AS Direccion,
TELEFONO_PERSONA.NUM_PERSONA AS Telefono,
CLIENTE.FECHA_REGISTRO AS Fecha_Registro_Cliente,
MASCOTA.ID_MASCOTA AS ID_Mascota,
MASCOTA.NOMBRE_MASCOTA AS Nombre_Mascota,
MASCOTA.ESPECIE AS Especie_Mascota,
MASCOTA.RAZA AS Raza_Mascota,
MASCOTA.FECHA_NACIMIENTO AS Fecha_Nacimiento_Mascota,
MASCOTA.PESO_ACTUAL AS Peso_Mascota

FROM CLIENTE
JOIN PERSONA ON CLIENTE.CEDULA_CLIENTE = PERSONA.CEDULA
LEFT JOIN TELEFONO_PERSONA ON PERSONA.CEDULA = TELEFONO_PERSONA.CEDULA_PERSONA
LEFT JOIN MASCOTA ON CLIENTE.CEDULA_CLIENTE = MASCOTA.CEDULA_CLIENTE;

Select * from vw_Directorio_General





--Funcion 1--

CREATE FUNCTION fn_Calcular_Edad (@FechaNacimiento DATE)
RETURNS INT 
AS
BEGIN
DECLARE @Edad INT
IF @FechaNacimiento IS NULL
RETURN NULL;

SET @Edad=(
CAST(CONVERT(VARCHAR(10), GETDATE(), 112) AS INT)
- CAST(CONVERT(VARCHAR(10), @FechaNacimiento, 112) AS INT))/10000;
RETURN @Edad;
END

SELECT MASCOTA.NOMBRE_MASCOTA, MASCOTA.FECHA_NACIMIENTO, dbo.fn_Calcular_Edad(FECHA_NACIMIENTO) AS Edad
FROM MASCOTA


--Funcion 2--

CREATE FUNCTION fn_Calcular_Total_Insumos(@IDCita INT)
RETURNS DECIMAL(10, 2)
AS
BEGIN
DECLARE @TotalGastado DECIMAL(10, 2);

SELECT @TotalGastado = SUM(INSUMO_CONSUMIDO.Cantidad_Utilizada * INSUMO.PRECIO_UNITARIO)
FROM INSUMO_CONSUMIDO
JOIN INSUMO ON INSUMO_CONSUMIDO.ID_Insumo = INSUMO.ID_INSUMO
WHERE INSUMO_CONSUMIDO.ID_Cita = @IDCita;

RETURN ISNULL(@TotalGastado, 0.00);
END;

SELECT dbo.fn_Calcular_Total_Insumos(1) AS Total